{% set name = "perl-digest-md5" %}
{% set version = "2.59" %}
{% set sha256 = "b5ecba079bd5907d52663a659cd977b6247526abe6aed9b818d083dd99af77d2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TO/TODDR/Digest-MD5-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # nothing provides perl >=5.32.1,<6.0a0 *_perl5 needed by perl-extutils-makemaker-7.36-pl5321hd8ed1ab_0
  skip: true  # [win]
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Digest::MD5

about:
  home: https://metacpan.org/dist/Digest-MD5
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: 'Perl interface to the MD-5 algorithm'
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
